### Here we are exploring the markov chain rule with the fixed repeated probabilities

In [2]:
import numpy as np

#### A,B,C are the existing products and X being the new product launched on  market
Below is the calculated probabilities of the rotation about the each product in market

| Store | A  | B  | C  | X  |
|-------|----|----|----|----|
|  A    |0.92|0.03|0.02|0.01|
|  B    |0.02|0.94|0.02|0.01|
|  C    |0.01|0.01|0.90|0.01|
|  X    |0.05|0.02|0.06|0.97|

To represent that in percentages of market share of each product will be as below

| Store| Customers|
|------|------|
|   A  | 0.40 |
|   B  | 0.32 |
|   C  | 0.18 |
|   X  | 0.10 |

In [35]:
#define the matrices for the data
prodcuts_share = np.array([0.40,0.32,0.18,0.10])
probability_matrix = np.array([[0.92,0.03,0.02,0.01],[0.02,0.94,0.02,0.01],[0.01,0.01,0.90,0.01],[0.05,0.02,0.06,0.97]])

In [37]:
print('The probability_matrix of customers turn around in following week is')
probability_matrix

The probability_matrix of customers turn around in following week is


array([[0.92, 0.03, 0.02, 0.01],
       [0.02, 0.94, 0.02, 0.01],
       [0.01, 0.01, 0.9 , 0.01],
       [0.05, 0.02, 0.06, 0.97]])

In [38]:
print(prodcuts_share.shape)
print(probability_matrix.shape)

(4,)
(4, 4)


In [62]:
## define the function for validating the resultant probabilities
def validate_res(res):
    total_prob = np.sum(res,axis=0)  
    return True if (total_prob>= 0.99  and total_prob<=1.001) else False

### obsolutely there is an another way aound for this markov chain calculations given that the initial probability never changes.

state_x_time = x0 * p^(time)

* Where time refers to the future time stamp

In [39]:
def mat_mutiply(in_mat,time):
    in_copy = np.copy(in_mat)  
    res = np.copy(in_mat)
    for _ in range(1,time):
        res = np.dot(res,in_copy)
    return res

In [65]:
prob_3_time = mat_mutiply(probability_matrix,120)
state_3_time = np.dot(prob_3_time,prodcuts_share)
print(validate_res(state_3_time))
state_3_time

True


array([0.16101649, 0.17892225, 0.09090917, 0.56915209])

In [12]:
probability_matrix

array([[0.92, 0.02, 0.01, 0.05],
       [0.03, 0.94, 0.01, 0.02],
       [0.02, 0.02, 0.9 , 0.06],
       [0.01, 0.01, 0.01, 0.97]])

In [64]:
np.sum(state_3_time)

0.9999999999999989