### Here we are exploring the markov chain rule with the fixed repeated probabilities

In [1]:
import numpy as np

### Store and their customers is the example in this book
#### Stores are A,B,C

| Store | Probability of Repetiotion | Exit to other Stores | Initial Customers|
|-------|----------------------------|----------------------|------------------|
|  A    | 80%                        | B-10% C-10%          | 200              |
|  B    | 70%                        | A-20% C-10%          | 120              |
|  C    | 60%                        | B-30% A-10%          | 180              |

* Total number of customeres are 200+120+180 = 500
 To represent that in percentages will be as below

| Store| Customers|
|------|------|
|   A  | 0.40 |
|   B  | 0.24 |
|   C  | 0.36 |

In [47]:
#define the matrices for the data
customers_to_stores_raw = np.array([200,120,180])
cutomers_to_stores = np.array([0.40,0.24,0.36])
probability_matrix = np.array([[0.8,0.2,0.1],[0.1,0.7,0.3],[0.1,0.1,0.6]])

In [3]:
print('The probability_matrix of customers turn around in following week is')
probability_matrix

The probability_matrix of customers turn around in following week is


array([[0.8, 0.2, 0.1],
       [0.1, 0.7, 0.3],
       [0.1, 0.1, 0.6]])

In [4]:
print(cutomers_to_stores.shape)
print(probability_matrix.shape)

(3,)
(3, 3)


In [5]:
## define the matrix for recursive calculation of the probabilities.
def calc_next_probability(prob_mtx,feature_mtx):
    if((prob_mtx.shape[0] != feature_mtx.shape[0])):
        print('the matrix dimensions are mismatching')
        print('probability matrix dim are:{}'.format(prob_mtx.shape))
        print('feature_mtx matrix dim are:{}'.format(feature_mtx.shape))
    return np.dot(prob_mtx ,feature_mtx)

In [6]:
## define the function for validating the resultant probabilities
def validate_res(res):
    total_prob = np.sum(res,axis=0)  
    return True if (total_prob<=1.001) else False

In [7]:
result = calc_next_probability(probability_matrix ,cutomers_to_stores)

In [8]:
validate_res(result)

True

In [96]:
##now do the calculations for n iterations
iter_n  = 1000
customer_prob = np.copy(cutomers_to_stores)
c = 0
for i in range(iter_n):
    result = calc_next_probability(probability_matrix ,customer_prob)
    print(result)
    print(validate_res(result))
    if(round(customer_prob[0]*(10**3)) == round(result[0]*(10**3)) and c>5):
        print('same result is repeated for 5 cycles after cycle {}'.format(i-5))        
        break
    elif (round(customer_prob[0]*(10**3)) == round(result[0]*(10**3))):
            c = c+1       
    customer_prob = result

    

[0.404 0.316 0.28 ]
True
[0.4144 0.3456 0.24  ]
True
[0.42464 0.35536 0.22   ]
True
[0.432784 0.357216 0.21    ]
True
[0.4386704 0.3563296 0.205    ]
True
[0.44270224 0.35479776 0.2025    ]
True
[0.44537134 0.35337866 0.20125   ]
True
[0.44709781 0.35227719 0.200625  ]
True
[0.44819618 0.35149132 0.2003125 ]
True
[0.44888646 0.35095729 0.20015625]
True
[0.44931625 0.35060562 0.20007813]
True
[0.44958194 0.350379   0.20003906]
True
[0.44974526 0.35023521 0.20001953]
True
[0.4498452  0.35014503 0.20000977]
True
[0.44990614 0.35008897 0.20000488]
True
[0.4499432  0.35005436 0.20000244]
True
[0.44996567 0.3500331  0.20000122]
True
[0.44997928 0.35002011 0.20000061]
True
same result is repeated for 5 cycles after cycle 12


In [11]:
round(result[0]*(10**3)) == round(result[0]*(10**3)) 

True

### obsolutely there is an another way aound for this markov chain calculations given that the initial probability never changes.

state_x_time = x0 * p^(time)

* Where time refers to the future time stamp

In [102]:
def mat_mutiply(in_mat,time):
    in_copy = np.copy(in_mat)  
    res = np.copy(in_mat)
    for _ in range(1,time):
        res = np.dot(res,in_copy)
    return res

In [109]:
prob_3_time = mat_mutiply(probability_matrix,20)
state_3_time = np.dot(prob_3_time,cutomers_to_stores)
state_3_time

array([0.44999247, 0.35000737, 0.20000015])